# Generated by Django 3.1.3 on 2021-09-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0015_auto_20201019_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudevent',
            name='user_ip_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User IP address'),
        ),
    ]
